# Generated by Django 3.1.7 on 2021-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='pin',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
