# Generated by Django 3.1.7 on 2021-03-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
